//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoldTheAllergen.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergen
    {
        public Allergen()
        {
            this.Ingredients = new HashSet<RestaurantIngredient>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<RestaurantIngredient> Ingredients { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
