//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoldTheAllergen.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoldTheAllergenEntities : DbContext
    {
        public HoldTheAllergenEntities()
            : base("name=HoldTheAllergenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Allergen> Allergens { get; set; }
        public DbSet<MenuItem> MenuItems { get; set; }
        public DbSet<RestaurantIngredient> RestaurantIngredients { get; set; }
        public DbSet<Restaurant> Restaurants { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserStarredMenuItem> UserStarredMenuItems { get; set; }
    }
}
