//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoldTheAllergen.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.Ingredients = new HashSet<RestaurantIngredient>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public string GroupName { get; set; }
        public string UrlSlug { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<RestaurantIngredient> Ingredients { get; set; }
    }
}
