//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoldTheAllergen.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantIngredient
    {
        public RestaurantIngredient()
        {
            this.Allergens = new HashSet<Allergen>();
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<Allergen> Allergens { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
}
