//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoldTheAllergen.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.MenuItems = new HashSet<MenuItem>();
            this.Ingredients = new HashSet<RestaurantIngredient>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Notes { get; set; }
        public string UrlSlug { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<RestaurantIngredient> Ingredients { get; set; }
    }
}
